<a href="https://colab.research.google.com/github/BooEiEi/data_viz_2022/blob/main/Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Structure (โครงสร้างข้อมูล)
การเก็บข้อมูลหลายๆ ตัวด้วยกันอย่างเป็นระเบียบ

## list()
- เก็บอะไรก็ได้
- ลำดับในการเก็บ มีความสำคัญ

In [ ]:
list_a = [1,2,3,4,5,6] #[] square brackets

In [ ]:
list_a

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b = ['ab',2,3.14,list_a] # สามารถเอาอะไรมาเก็บใน list ก็ได้ เช่น string float

In [ ]:
list_b

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

## indexing การชี้สามชิกใน list ด้วยเลขลำดับของ list

In [ ]:
list_a[3]  #ลำดับเริ่มจาก 0

4

In [ ]:
list_b[3]

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b[3][4]

5

In [ ]:
list _a[6] #ไม่มีข้อมูลตำแหน่งที่ 6 ทำให้ error

SyntaxError: ignored

In [ ]:
list_a[-1] # index -1 คือตัวสุดท้ายของ list

6

In [ ]:
list_a[-2] # indexติดลบ คือแสดงข้อมูลจากหลังมาหน้า

5

### การสร้าง list()

In [ ]:
list_x1 = [] # แบบที่ 1
list_x2 = list() # แบบที่2

In [ ]:
print(list_x1)
print(list_x2)

[]
[]


### เพิ่มสมาชิกเข้าไปใน list ด้วย append()

In [ ]:
list_x1.append(2)

In [ ]:
list_x1

[2]

In [ ]:
list_x1.append(4)
print(list_x1)

[2, 4]


In [ ]:
list_x1[0]

2

In [ ]:
list_x1[-1]

4

### ลบสมาชิกจาก list

In [ ]:
list_x2.append('ha') 

In [ ]:
list_x2 #รัน2 ครั้ง ข้อมูลในlist เพิ่มขึ้น

['ha', 'ha']

In [ ]:
list_x2.pop() # pop คือลบตัวหลังสุดออก

'ha'

In [ ]:
list_x2
print(list_x2)

['ha']


In [ ]:
list_x1
print(list_x1)

[2, 4]


### len() ตรวจสอบจำนวนสมาชิกของ list

In [ ]:
print(list_b)
print(len(list_b))

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]
4


In [ ]:
len(list_a)

6

### string is a list of characters

In [ ]:
st_stat = 'Department of Statistics, Faculty of Science'

In [ ]:
st_stat[10]

' '

In [ ]:
len(st_stat)

44

### List Slicing ' : '

- list[จุดเริ่มต้น (ทึบ):จุดสุดท้าย (โปร่ง)]
- list[จุดเริ่มต้น (ทึบ):จุดสุดท้าย (โปร่ง):step]

In [ ]:
list_a 

[1, 2, 3, 4, 5, 6]

In [ ]:
list_a[2]

3

#### : colon

In [ ]:
list_a[-3:] # : colon อยากได้ส่วนหนึ่งของ list ที่ไม่ใช่ 1 ตัว ใช้colon ใช้-3 ก็เรียงข้อมูลจากหน้าไปหลังอยู่ดี

[4, 5, 6]

In [ ]:
list_a[:4]

[1, 2, 3, 4]

In [ ]:
list_a[1:4]

[2, 3, 4]

In [ ]:
list_a[:] #ไม่ใส่อะไรคือเอาทุกตัว

[1, 2, 3, 4, 5, 6]

#### step

In [ ]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13]

In [ ]:
list_c[:10:] #ใส่ colonหน้าหลังคือเอาตัวที่10 ด้วย

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
list_c[:10:2] # หลัง colon ตัวสุดท้ายคือตัวที่1กับตัวที่2 ต่างกัน2หน่วย ไปเรื่อยๆ

[1, 3, 5, 7, 9]

In [ ]:
list_c[::-1]

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

### range()

In [ ]:
range(21)

range(0, 21)

In [ ]:
a = list(range(21))

In [ ]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
list(range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

## HW2 คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาให้สวยงาม)
- 12:30:15
- 13:41:07
- 09:11:50
- 21:30:15
- 03:10:15

In [ ]:
#ตัวอย่าง 01:02:03 

a = (1*60*60) + (2*60) +3
print(f'01:02:03 แบ่งเป็นวินาทีได้ {a} วินาที')

01:02:03 แบ่งเป็นวินาทีได้ 3723 วินาที


In [ ]:
#12:30:15
b = '12:30:15'
list_b = b.split(':')
b1 = (int(list_b[0])*60*60) + (int(list_b[1])*60) +int(list_b[2])
print(f'เวลา 21:30:15 สามารถแบ่งเป็นวินาทีได้ {b1} วินาที')

เวลา 21:30:15 สามารถแบ่งเป็นวินาทีได้ 45015 วินาที


In [ ]:
#13:41:07
c = '13:41:07'
list_c = c.split(':')
c1 = (int(list_c[0])*60*60) + (int(list_c[1])*60) +int(list_c[2])
print(f'เวลา 21:30:15 สามารถแบ่งเป็นวินาทีได้ {c1} วินาที')

เวลา 21:30:15 สามารถแบ่งเป็นวินาทีได้ 49267 วินาที


In [ ]:
#09:11:50
d = '09:11:50'
list_d = d.split(':')
d1 = (int(list_d[0])*60*60) + (int(list_d[1])*60) +int(list_d[2])
print(f'เวลา 21:30:15 สามารถแบ่งเป็นวินาทีได้ {d1} วินาที')

เวลา 21:30:15 สามารถแบ่งเป็นวินาทีได้ 33110 วินาที


In [ ]:
#21:30:15
e = '21:30:15'
list_e = e.split(':')
e1 = (int(list_e[0])*60*60) + (int(list_e[1])*60) +int(list_e[2])
print(f'เวลา 21:30:15 สามารถแบ่งเป็นวินาทีได้ {e1} วินาที')

เวลา 21:30:15 สามารถแบ่งเป็นวินาทีได้ 77415 วินาที


In [ ]:
#03:10:15
f = '03:10:15'
list_f = f.split(':')
f1 = (int(list_f[0])*60*60) + (int(list_f[1])*60) +int(list_f[2])
print(f'เวลา 21:30:15 สามารถแบ่งเป็นวินาทีได้ {f1} วินาที')

เวลา 21:30:15 สามารถแบ่งเป็นวินาทีได้ 11415 วินาที


In [ ]:
#ลองทำ
str1 = "1 3 5 7 9"
list1 = str1.split()
print(int(list1[1])*3)

9


## Dictionary

- คล้าย list()
- index เป็นอะไรก็ได้ ไม่จำเป็นต้องเป็นตัวลำดับ
- ลำดับไม่มีความสำคัญ

### สร้าง Dictionary

### การชี้ สมาชิกใน DIctionary

In [1]:
dict_a = {1:'Happy','N':'New','2022':'Year'} # { }  curly brackets

In [2]:
dict_a[1]

'Happy'

In [3]:
dict_a['N']

'New'

In [4]:
dict_a["2022"]

'Year'

In [5]:
dict_a.keys() #.keys() เรียกดูสมาชิกทั้งหมดว่ามี index อะไรบ้าง

dict_keys([1, 'N', '2022'])

In [9]:
dict_a.values() # .values() บอกค่าที่อยู่ใน dict

dict_values(['Happy', 'New', 'Year', 3.14])

### การเพิ่มสมาชิกลงไปใน DIctionary

In [10]:
dict_a[7] = 3.14

In [7]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

In [12]:
dict_a["N"] = "NNNNEWWWW"

In [13]:
dict_a # เมื่อใช้ index ซ้ำมันค่าบันทึกค่าใหม่แทนที่ค่าเดิม

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'NNNNEWWWW'}

## Numpy Array

- เก็บได้แค่ตัวเลข
- อ้างอิงโดยใช้พิกัด (2มิติ ก็มองเป็น Matrix)

In [14]:
import numpy # ใช้code ของคนอื่นที่เขียนไว้

### 1D array

In [15]:
arr_a = numpy.array([1,2,3,4,5])

In [16]:
arr_a

array([1, 2, 3, 4, 5])

In [17]:
arr_a[0]

1

In [18]:
list_A = [5,6,7,8,9] # ใช้ list ได้เหมือนกัน
arr_b = numpy.array(list_A)
arr_b

array([5, 6, 7, 8, 9])

In [19]:
5 * arr_a # Matrix (scalar multiplication)

array([ 5, 10, 15, 20, 25])

In [20]:
5*list_A # list จะต่างกับ arr ตรงนี้

[5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9]

In [21]:
arr_c = numpy.array([10,20,30,40,50])

In [22]:
print(arr_a)

[1 2 3 4 5]


In [23]:
arr_a + arr_c #matrix บวก matrix 

array([11, 22, 33, 44, 55])

In [30]:
arr_a.shape

(5,)

### 2D arrary

In [24]:
import numpy as np # import แต่เปลี่ยนชื่อให้มันสั้นสะดวกต่อการพิมพ์

In [26]:
arr2_z = np.array([[1,2,3],[4,5,6]])

In [27]:
arr2_z

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr2_z.shape

(2, 3)

### np.zeros()

In [31]:
arr2_3_5_0 =np.zeros((3,5))

In [32]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
arr2_3_5_0[1,2] = 9

In [36]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
arr2_3_5_0[1,2]

9.0

In [38]:
print(list_A)# เปลี่ยน ค่าใน list()
list_A[-1] = 'christmas'
print(list_A)

[5, 6, 7, 8, 9]
[5, 6, 7, 8, 'christmas']


###  np.ones()

In [39]:
arr2_4_5_1 = np.ones((4,5))

In [40]:
arr2_4_5_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
arr2_4_5_200 = 200*np.ones((4,5))

In [42]:
arr2_4_5_200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

### Matrix operations

#### การบวก ลบ matrix $M \pm N$ บวกลบตัวที่อยู่ตำแหน่งเดียวกัน

In [44]:
arr2_4_5_200 + arr2_3_5_0 # บวกลบกันไม่ได้ เพราะ ขนาดไม่เท่ากัน

ValueError: ignored

In [45]:
arr2_4_5_200 + arr2_4_5_1

array([[201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.]])

#### การคูณ matrix 
- $aM$  scalar คูณ Matrix (scalar คูณกระจายเข้าไปทุกตัวของ Matrix) 
- $M \times N$คูณ Matrix (แถวคูณหลัก)

$aM$

In [46]:
5 * arr_a

array([ 5, 10, 15, 20, 25])

$M \times N$
- (m,n) $\times$ (n,o) = (m,o)

In [47]:
mat_a = np.array([[2,3,5],[4,6,7]])
mat_b = np.array([[1,2,5],[2,4,-7]])
mat_c = np.array([[2,3,],[4,6],[7,9]])

In [48]:
mat_a

array([[2, 3, 5],
       [4, 6, 7]])

In [50]:
mat_b

array([[ 1,  2,  5],
       [ 2,  4, -7]])

In [49]:
mat_c

array([[2, 3],
       [4, 6],
       [7, 9]])

axc, bxc

In [51]:
np.dot(mat_a,mat_c)

array([[ 51,  69],
       [ 81, 111]])

In [52]:
np.dot(mat_b,mat_c)

array([[ 45,  60],
       [-29, -33]])

cxa, cxb

In [53]:
np.dot(mat_c,mat_a)

array([[16, 24, 31],
       [32, 48, 62],
       [50, 75, 98]])

In [54]:
np.dot(mat_c,mat_b)

array([[  8,  16, -11],
       [ 16,  32, -22],
       [ 25,  50, -28]])

In [64]:
mat_X = np.dot(mat_c,mat_b)
print(mat_X)

[[  8  16 -11]
 [ 16  32 -22]
 [ 25  50 -28]]


In [56]:
mat_a * mat_b # คูณตัวตำแหน่งเดียวกัน ใช้ไม่ได้

array([[  2,   6,  25],
       [  8,  24, -49]])

### Matrix Slicing

In [65]:
mat_X[:2,:2]

array([[ 8, 16],
       [16, 32]])

HW 3 

1. สร้าง array ที่เป็นรูปต้น chrismas
2. slice เลข 1 ออกมาจาก array HW3

In [59]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [63]:
HW3[::4,2] = 1
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## panda Dataframe (แยกออกไปเป็น Notebook เฉพาะ)